### ISSUE TITLE
missing lib.tools

### ISSUE THREAD

**Issue by theokirkland** [comprna/SUPPA#183]
I am trying to run SUPPA on a mac.  I have the program installed with conda.  When I run the following command 

theoneal@MacBook-Pro ~/opt/anaconda3/pkgs/suppa-2.3-py36_1/bin
$ python3 suppa.py --help

I get

$ python3 suppa.py --help
Traceback (most recent call last):
  File "/Users/theoneal/opt/anaconda3/pkgs/suppa-2.3-py36_1/bin/suppa.py", line 11, in <module>
    import psiPerGene as psiPerIsoform
  File "/Users/theoneal/opt/anaconda3/pkgs/suppa-2.3-py36_1/bin/psiPerGene.py", line 14, in <module>
    from lib.tools import *
ModuleNotFoundError: No module named 'lib'

Any ideas?

Thanks  Theo

**Comment by EduEyras** [comment]
Apologies for not responding earlier

Have you tried alternative ways of setting up SUPPA?
It may be easier to simply download the current version of the code.

Thanks

Eduardo
