### ISSUE TITLE
Error when installing statsmodels

### ISSUE THREAD

**Issue by igonzalsbmc** [comprna/SUPPA#194]
Could you help me to know why I'm getting this error during the installation of SUPPA==2.3?

```
5.859 Collecting statsmodels>=0.6.1 (from SUPPA==2.3)
6.026   Downloading https://files.pythonhosted.org/packages/53/1c/b83f6a4632b502a20b0f83bc5c25ebfa03eebd00efe9b45fcdcde1a0ab40/statsmodels-0.11.0.tar.gz (15.4MB)
8.064   Installing build dependencies: started
71.37   Installing build dependencies: still running...
180.0   Installing build dependencies: still running...
240.0   Installing build dependencies: still running...
246.8   Installing build dependencies: finished with status 'done'
246.8   Getting requirements to build wheel: started
262.3   Getting requirements to build wheel: finished with status 'error'
262.3   ERROR: Complete output from command /usr/local/bin/python /usr/local/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpvk1tv64y:
262.3   ERROR: performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:83:5: Exception check on 'dhamilton_filter_log_iteration' will always require the GIL to be acquired.
262.3   Possible solutions:
262.3           1. Declare 'dhamilton_filter_log_iteration' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3           2. Use an 'int' return type on 'dhamilton_filter_log_iteration' to allow an error code to be returned.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:231:5: Exception check on 'chamilton_filter_log_iteration' will always require the GIL to be acquired.
262.3   Possible solutions:
262.3           1. Declare 'chamilton_filter_log_iteration' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3           2. Use an 'int' return type on 'chamilton_filter_log_iteration' to allow an error code to be returned.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:379:5: Exception check on 'shamilton_filter_log_iteration' will always require the GIL to be acquired.
262.3   Possible solutions:
262.3           1. Declare 'shamilton_filter_log_iteration' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3           2. Use an 'int' return type on 'shamilton_filter_log_iteration' to allow an error code to be returned.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:527:5: Exception check on 'zhamilton_filter_log_iteration' will always require the GIL to be acquired.
262.3   Possible solutions:
262.3           1. Declare 'zhamilton_filter_log_iteration' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3           2. Use an 'int' return type on 'zhamilton_filter_log_iteration' to allow an error code to be returned.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:71:42: Exception check after calling 'dhamilton_filter_log_iteration' will always require the GIL to be acquired.
262.3   Possible solutions:
262.3           1. Declare 'dhamilton_filter_log_iteration' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3           2. Use an 'int' return type on 'dhamilton_filter_log_iteration' to allow an error code to be returned.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:214:32: Exception check after calling 'zexp' will always require the GIL to be acquired. Declare 'zexp' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:217:26: Exception check after calling 'zlog' will always require the GIL to be acquired. Declare 'zlog' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:219:42: Exception check after calling 'chamilton_filter_log_iteration' will always require the GIL to be acquired.
262.3   Possible solutions:
262.3           1. Declare 'chamilton_filter_log_iteration' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3           2. Use an 'int' return type on 'chamilton_filter_log_iteration' to allow an error code to be returned.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:277:22: Exception check after calling 'zexp' will always require the GIL to be acquired. Declare 'zexp' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:280:18: Exception check after calling 'zlog' will always require the GIL to be acquired. Declare 'zlog' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:303:14: Exception check after calling 'zexp' will always require the GIL to be acquired. Declare 'zexp' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:304:41: Exception check after calling 'zlog' will always require the GIL to be acquired. Declare 'zlog' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:367:42: Exception check after calling 'shamilton_filter_log_iteration' will always require the GIL to be acquired.
262.3   Possible solutions:
262.3           1. Declare 'shamilton_filter_log_iteration' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3           2. Use an 'int' return type on 'shamilton_filter_log_iteration' to allow an error code to be returned.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:510:32: Exception check after calling 'zexp' will always require the GIL to be acquired. Declare 'zexp' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:513:26: Exception check after calling 'zlog' will always require the GIL to be acquired. Declare 'zlog' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:515:42: Exception check after calling 'zhamilton_filter_log_iteration' will always require the GIL to be acquired.
262.3   Possible solutions:
262.3           1. Declare 'zhamilton_filter_log_iteration' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3           2. Use an 'int' return type on 'zhamilton_filter_log_iteration' to allow an error code to be returned.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:573:22: Exception check after calling 'zexp' will always require the GIL to be acquired. Declare 'zexp' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:576:18: Exception check after calling 'zlog' will always require the GIL to be acquired. Declare 'zlog' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:599:14: Exception check after calling 'zexp' will always require the GIL to be acquired. Declare 'zexp' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3   performance hint: statsmodels/tsa/regime_switching/_hamilton_filter.pyx:600:41: Exception check after calling 'zlog' will always require the GIL to be acquired. Declare 'zlog' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3   performance hint: statsmodels/tsa/regime_switching/_kim_smoother.pyx:56:5: Exception check on 'dkim_smoother_log_iteration' will always require the GIL to be acquired.
262.3   Possible solutions:
262.3           1. Declare 'dkim_smoother_log_iteration' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3           2. Use an 'int' return type on 'dkim_smoother_log_iteration' to allow an error code to be returned.
262.3   performance hint: statsmodels/tsa/regime_switching/_kim_smoother.pyx:155:5: Exception check on 'ckim_smoother_log_iteration' will always require the GIL to be acquired.
262.3   Possible solutions:
262.3           1. Declare 'ckim_smoother_log_iteration' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3           2. Use an 'int' return type on 'ckim_smoother_log_iteration' to allow an error code to be returned.
262.3   performance hint: statsmodels/tsa/regime_switching/_kim_smoother.pyx:254:5: Exception check on 'skim_smoother_log_iteration' will always require the GIL to be acquired.
262.3   Possible solutions:
262.3           1. Declare 'skim_smoother_log_iteration' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3           2. Use an 'int' return type on 'skim_smoother_log_iteration' to allow an error code to be returned.
262.3   performance hint: statsmodels/tsa/regime_switching/_kim_smoother.pyx:353:5: Exception check on 'zkim_smoother_log_iteration' will always require the GIL to be acquired.
262.3   Possible solutions:
262.3           1. Declare 'zkim_smoother_log_iteration' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3           2. Use an 'int' return type on 'zkim_smoother_log_iteration' to allow an error code to be returned.
262.3   performance hint: statsmodels/tsa/regime_switching/_kim_smoother.pyx:46:39: Exception check after calling 'dkim_smoother_log_iteration' will always require the GIL to be acquired.
262.3   Possible solutions:
262.3           1. Declare 'dkim_smoother_log_iteration' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3           2. Use an 'int' return type on 'dkim_smoother_log_iteration' to allow an error code to be returned.
262.3   performance hint: statsmodels/tsa/regime_switching/_kim_smoother.pyx:145:39: Exception check after calling 'ckim_smoother_log_iteration' will always require the GIL to be acquired.
262.3   Possible solutions:
262.3           1. Declare 'ckim_smoother_log_iteration' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3           2. Use an 'int' return type on 'ckim_smoother_log_iteration' to allow an error code to be returned.
262.3   performance hint: statsmodels/tsa/regime_switching/_kim_smoother.pyx:213:20: Exception check after calling 'zexp' will always require the GIL to be acquired. Declare 'zexp' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3   performance hint: statsmodels/tsa/regime_switching/_kim_smoother.pyx:216:18: Exception check after calling 'zlog' will always require the GIL to be acquired. Declare 'zlog' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3   performance hint: statsmodels/tsa/regime_switching/_kim_smoother.pyx:244:39: Exception check after calling 'skim_smoother_log_iteration' will always require the GIL to be acquired.
262.3   Possible solutions:
262.3           1. Declare 'skim_smoother_log_iteration' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3           2. Use an 'int' return type on 'skim_smoother_log_iteration' to allow an error code to be returned.
262.3   performance hint: statsmodels/tsa/regime_switching/_kim_smoother.pyx:343:39: Exception check after calling 'zkim_smoother_log_iteration' will always require the GIL to be acquired.
262.3   Possible solutions:
262.3           1. Declare 'zkim_smoother_log_iteration' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3           2. Use an 'int' return type on 'zkim_smoother_log_iteration' to allow an error code to be returned.
262.3   performance hint: statsmodels/tsa/regime_switching/_kim_smoother.pyx:411:20: Exception check after calling 'zexp' will always require the GIL to be acquired. Declare 'zexp' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3   performance hint: statsmodels/tsa/regime_switching/_kim_smoother.pyx:414:18: Exception check after calling 'zlog' will always require the GIL to be acquired. Declare 'zlog' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions.
262.3   
262.3   Error compiling Cython file:
262.3   ------------------------------------------------------------
262.3   ...
262.3       kfilter._tmp2[0] = scalar * kfilter._forecast_error[0]
262.3       blas.dcopy(&model._k_endogstates, model._design, &inc, kfilter._tmp3, &inc)
262.3       blas.dscal(&model._k_endogstates, &scalar, kfilter._tmp3, &inc)
262.3   
262.3       if not (kfilter.conserve_memory & MEMORY_NO_STD_FORECAST > 0):
262.3           kfilter._standardized_forecast_error[0] = kfilter._forecast_error[0] * scalar**0.5
262.3                                                                                ^
262.3   ------------------------------------------------------------
262.3   
262.3   statsmodels/tsa/statespace/_filters/_inversions.pyx:58:77: Cannot assign type 'npy_float64 complex' to 'float64_t' (alias of 'double')
262.3   Compiling statsmodels/nonparametric/linbin.pyx because it changed.
262.3   Compiling statsmodels/tsa/_exponential_smoothers.pyx because it changed.
262.3   Compiling statsmodels/tsa/kalmanf/kalman_loglike.pyx because it changed.
262.3   Compiling statsmodels/tsa/_innovations.pyx because it changed.
262.3   Compiling statsmodels/tsa/regime_switching/_kim_smoother.pyx because it changed.
262.3   Compiling statsmodels/nonparametric/_smoothers_lowess.pyx because it changed.
262.3   Compiling statsmodels/tsa/_stl.pyx because it changed.
262.3   Compiling statsmodels/tsa/innovations/_arma_innovations.pyx because it changed.
262.3   Compiling statsmodels/tsa/regime_switching/_hamilton_filter.pyx because it changed.
262.3   Compiling statsmodels/tsa/statespace/_initialization.pyx because it changed.
262.3   Compiling statsmodels/tsa/statespace/_representation.pyx because it changed.
262.3   Compiling statsmodels/tsa/statespace/_kalman_filter.pyx because it changed.
262.3   Compiling statsmodels/tsa/statespace/_filters/_conventional.pyx because it changed.
262.3   Compiling statsmodels/tsa/statespace/_filters/_inversions.pyx because it changed.
262.3   Compiling statsmodels/tsa/statespace/_filters/_univariate.pyx because it changed.
262.3   Compiling statsmodels/tsa/statespace/_filters/_univariate_diffuse.pyx because it changed.
262.3   Compiling statsmodels/tsa/statespace/_kalman_smoother.pyx because it changed.
262.3   Compiling statsmodels/tsa/statespace/_smoothers/_alternative.pyx because it changed.
262.3   Compiling statsmodels/tsa/statespace/_smoothers/_classical.pyx because it changed.
262.3   Compiling statsmodels/tsa/statespace/_smoothers/_conventional.pyx because it changed.
262.3   Compiling statsmodels/tsa/statespace/_smoothers/_univariate.pyx because it changed.
262.3   Compiling statsmodels/tsa/statespace/_smoothers/_univariate_diffuse.pyx because it changed.
262.3   Compiling statsmodels/tsa/statespace/_simulation_smoother.pyx because it changed.
262.3   Compiling statsmodels/tsa/statespace/_tools.pyx because it changed.
262.3   [ 1/24] Cythonizing statsmodels/nonparametric/_smoothers_lowess.pyx
262.3   [ 2/24] Cythonizing statsmodels/nonparametric/linbin.pyx
262.3   [ 3/24] Cythonizing statsmodels/tsa/_exponential_smoothers.pyx
262.3   [ 4/24] Cythonizing statsmodels/tsa/_innovations.pyx
262.3   [ 5/24] Cythonizing statsmodels/tsa/_stl.pyx
262.3   [ 6/24] Cythonizing statsmodels/tsa/innovations/_arma_innovations.pyx
262.3   [ 7/24] Cythonizing statsmodels/tsa/kalmanf/kalman_loglike.pyx
262.3   [ 8/24] Cythonizing statsmodels/tsa/regime_switching/_hamilton_filter.pyx
262.3   [ 9/24] Cythonizing statsmodels/tsa/regime_switching/_kim_smoother.pyx
262.3   [10/24] Cythonizing statsmodels/tsa/statespace/_filters/_conventional.pyx
262.3   [11/24] Cythonizing statsmodels/tsa/statespace/_filters/_inversions.pyx
262.3   Traceback (most recent call last):
262.3     File "/usr/local/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
262.3       main()
262.3     File "/usr/local/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
262.3       json_out['return_val'] = hook(**hook_input['kwargs'])
262.3     File "/usr/local/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
262.3       return hook(config_settings)
262.3     File "/tmp/pip-build-env-av1u8509/overlay/lib/python3.4/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
262.3       return self._get_build_requires(config_settings, requirements=['wheel'])
262.3     File "/tmp/pip-build-env-av1u8509/overlay/lib/python3.4/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
262.3       self.run_setup()
262.3     File "/tmp/pip-build-env-av1u8509/overlay/lib/python3.4/site-packages/setuptools/build_meta.py", line 237, in run_setup
262.3       self).run_setup(setup_script=setup_script)
262.3     File "/tmp/pip-build-env-av1u8509/overlay/lib/python3.4/site-packages/setuptools/build_meta.py", line 142, in run_setup
262.3       exec(compile(code, __file__, 'exec'), locals())
262.3     File "setup.py", line 296, in <module>
262.3       language_level=3, force=CYTHON_COVERAGE)
262.3     File "/tmp/pip-build-env-av1u8509/overlay/lib/python3.4/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
262.3       cythonize_one(*args)
262.3     File "/tmp/pip-build-env-av1u8509/overlay/lib/python3.4/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
262.3       raise CompileError(None, pyx_file)
262.3   Cython.Compiler.Errors.CompileError: statsmodels/tsa/statespace/_filters/_inversions.pyx
262.3   ----------------------------------------
262.4 ERROR: Command "/usr/local/bin/python /usr/local/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpvk1tv64y" failed with error code 1 in /tmp/pip-install-8so65uls/statsmodels
```

**Comment by EduEyras** [comment]
Are you trying pip install?

Have you tried doing a copy of the code directly? There might be things in
the pip install not working in this case.

E.

**Comment by igonzalsbmc** [comment]
That worked! Thank you!
